stages:
  - test
  - qa-automation

# Stage 1: Menguji Unit Test Backend Go
test_backend:
  stage: test
  image: golang:1.25 
  script:
    - cd apps/core-backend
    - go mod download
    - go test -v ./...

# Stage 2: Menguji Smart Contract Solidity
test_blockchain:
  stage: test
  image: node:20
  script:
    - cd blockchain
    - npm install
    - npx hardhat test

# Stage 3: Menguji Unit Test Frontend Next.js (Jest)
test_frontend:
  stage: test
  image: node:20
  script:
    - cd apps/web-frontend
    - npm install
    - npm run test

# Stage 4: Menjalankan Playwright E2E (Akan aktif jika semua unit test di atas lulus)
e2e_playwright:
  stage: qa-automation
  image: mcr.microsoft.com/playwright:v1.42.0-jammy
  script:
    - cd e2e-qa
    - npm install
    - npx playwright test