stages:
  - test
  - qa-automation

# Stage 1: Menguji Unit Test Backend Go (SUDAH DISINKRONKAN)
test_backend:
  stage: test
  image: golang:1.25 # Menggunakan versi stabil rilis terbaru 2025/2026
  script:
    - cd apps/core-service # <- KALIBRASI: Dari core-backend diubah ke core-service
    - go mod download
    - go test -v ./...

# Stage 2: Menguji Smart Contract Solidity (Diberi toleransi karena folder belum dibuat)
test_blockchain:
  stage: test
  image: node:20
  allow_failure: true # <- TRIK: Agar pipeline tidak gagal total saat folder belum ada
  script:
    - if [ -d "blockchain" ]; then cd blockchain && npm install && npx hardhat test; else echo "Folder blockchain belum dibuat, skip test."; fi

# Stage 3: Menguji Unit Test Frontend Next.js (Diberi toleransi karena folder belum dibuat)
test_frontend:
  stage: test
  image: node:20
  allow_failure: true # <- TRIK: Mencegah pipeline macet di fase MVP
  script:
    - if [ -d "apps/dashboard-web" ]; then cd apps/dashboard-web && npm install && npm run test; else echo "Folder frontend belum dibuat, skip test."; fi

# Stage 4: Menjalankan Playwright E2E
e2e_playwright:
  stage: qa-automation
  image: mcr.microsoft.com/playwright:v1.42.0-jammy
  allow_failure: true
  script:
    - if [ -d "e2e-qa" ]; then cd e2e-qa && npm install && npx playwright test; else echo "Folder E2E belum dibuat, skip."; fi