package usecase_test

import (
	"context"
	"errors"
	"testing"

	"rekberkuy/core-service/internal/domain"
	"rekberkuy/core-service/internal/usecase"
)

// ============================================================================
// VENDOR USECASE — UNIT TESTS
// ============================================================================

func TestRegisterVendorProfile_Success(t *testing.T) {
	ctx := context.Background()

	var captured *domain.VendorProfile
	vendorRepo := &mockVendorRepo{
		onCreateVendor: func(ctx context.Context, v *domain.VendorProfile) error {
			captured = v
			return nil
		},
	}
	u := usecase.NewVendorUsecase(vendorRepo)

	input := &domain.VendorProfile{
		VendorID:     "vendor-uuid-1",
		BusinessName: "Katering Sedap",
		Category:     "CATERING",
		IsVerified:   true, // intentionally true to ensure the usecase forces it false
	}

	if err := u.RegisterVendorProfile(ctx, input); err != nil {
		t.Fatalf("expected success, got: %v", err)
	}
	if captured == nil {
		t.Fatal("CreateVendor was not called")
	}
	if captured.IsVerified {
		t.Error("IsVerified must be forced false before admin verification")
	}
}

func TestRegisterVendorProfile_EmptyBusinessName(t *testing.T) {
	ctx := context.Background()
	u := usecase.NewVendorUsecase(&mockVendorRepo{})

	if err := u.RegisterVendorProfile(ctx, &domain.VendorProfile{BusinessName: "", Category: "DECOR"}); err == nil {
		t.Fatal("expected error because BusinessName is empty")
	}
}

func TestRegisterVendorProfile_EmptyCategory(t *testing.T) {
	ctx := context.Background()
	u := usecase.NewVendorUsecase(&mockVendorRepo{})

	if err := u.RegisterVendorProfile(ctx, &domain.VendorProfile{BusinessName: "Foto Jaya", Category: ""}); err == nil {
		t.Fatal("expected error because Category is empty")
	}
}

// ============================================================================
// KYC USECASE — UNIT TESTS
// ============================================================================

func newKYCTestUsecase(kycRepo *mockKYCRepo, uow *mockUnitOfWork, client *mockKYCClient) *usecase.KYCUsecase {
	if uow == nil {
		uow = &mockUnitOfWork{}
	}
	if client == nil {
		client = &mockKYCClient{}
	}
	return usecase.NewKYCUsecase(kycRepo, uow, client)
}

func TestSubmitUserKYC_Success(t *testing.T) {
	ctx := context.Background()

	var captured *domain.KYCSubmission
	kycRepo := &mockKYCRepo{
		onSubmitKYC: func(ctx context.Context, k *domain.KYCSubmission) error {
			captured = k
			return nil
		},
	}
	u := newKYCTestUsecase(kycRepo, nil, nil)

	if err := u.SubmitUserKYC(ctx, "user-uuid-1", domain.RoleVerifiedMerchant, "3171010101900001", "https://cdn/ktp.jpg", "https://cdn/selfie.jpg"); err != nil {
		t.Fatalf("expected success, got: %v", err)
	}

	if captured == nil {
		t.Fatal("SubmitKYC was not called")
	}
	if captured.UserID != "user-uuid-1" {
		t.Errorf("UserID = %s, want user-uuid-1", captured.UserID)
	}
	if captured.TargetRole != domain.RoleVerifiedMerchant {
		t.Errorf("TargetRole = %s, want %s", captured.TargetRole, domain.RoleVerifiedMerchant)
	}
	if captured.Status != domain.KYCPending {
		t.Errorf("Status = %s, want PENDING", captured.Status)
	}
	if captured.ID == "" {
		t.Error("KYC ID must be generated by the usecase")
	}
}

func TestSubmitUserKYC_StoresAIReference(t *testing.T) {
	ctx := context.Background()

	var savedScore float64
	var savedReason string
	kycRepo := &mockKYCRepo{
		onSaveKYCAIResult: func(ctx context.Context, userID string, score float64, reason string) error {
			savedScore, savedReason = score, reason
			return nil
		},
	}
	client := &mockKYCClient{
		onVerify: func(ctx context.Context, userID, idCardURL, selfieURL string, role domain.UserRole) (float64, string, error) {
			return 0.87, "same-person-high-confidence", nil
		},
	}
	u := newKYCTestUsecase(kycRepo, nil, client)

	if err := u.SubmitUserKYC(ctx, "user-uuid-1", domain.RoleVerifiedVendor, "3171010101900002", "https://cdn/ktp.jpg", "https://cdn/selfie.jpg"); err != nil {
		t.Fatalf("expected success, got: %v", err)
	}
	if savedScore != 0.87 {
		t.Errorf("AI score = %f, want 0.87", savedScore)
	}
	if savedReason != "same-person-high-confidence" {
		t.Errorf("AI reason = %s, want same-person-high-confidence", savedReason)
	}
}

func TestSubmitUserKYC_AIUnavailableStillSucceeds(t *testing.T) {
	ctx := context.Background()

	aiResultSaved := false
	kycRepo := &mockKYCRepo{
		onSaveKYCAIResult: func(ctx context.Context, userID string, score float64, reason string) error {
			aiResultSaved = true
			return nil
		},
	}
	client := &mockKYCClient{
		onVerify: func(ctx context.Context, userID, idCardURL, selfieURL string, role domain.UserRole) (float64, string, error) {
			return 0, "", errors.New("backend-ai unreachable")
		},
	}
	u := newKYCTestUsecase(kycRepo, nil, client)

	// The AI is a reference only — its failure must NOT block the submission.
	if err := u.SubmitUserKYC(ctx, "user-uuid-1", domain.RoleVerifiedMerchant, "3171010101900003", "https://cdn/ktp.jpg", "https://cdn/selfie.jpg"); err != nil {
		t.Fatalf("submission must succeed when AI is unavailable, got: %v", err)
	}
	if aiResultSaved {
		t.Error("no AI result should be persisted when the AI service errors")
	}
}

func TestReviewKYC_ApprovePromotesRole(t *testing.T) {
	ctx := context.Background()

	kycRepo := &mockKYCRepo{
		onGetKYCByID: func(ctx context.Context, id string) (*domain.KYCSubmission, error) {
			return &domain.KYCSubmission{
				ID: id, UserID: "user-uuid-1",
				TargetRole: domain.RoleEventOrganizer,
				Status:     domain.KYCPending,
			}, nil
		},
	}
	userRepo := &mockUserRepo{
		onUpdateUserRole: func(ctx context.Context, id string, role domain.UserRole) error {
			if id != "user-uuid-1" {
				t.Errorf("role update for user %s, want user-uuid-1", id)
			}
			if role != domain.RoleEventOrganizer {
				t.Errorf("promoted role = %s, want %s", role, domain.RoleEventOrganizer)
			}
			return nil
		},
	}
	uow := &mockUnitOfWork{stores: domain.TxStores{KYC: kycRepo, Users: userRepo}}
	u := newKYCTestUsecase(kycRepo, uow, nil)

	reviewed, err := u.ReviewKYC(ctx, "admin-uuid", "kyc-uuid-1", domain.KYCApproved, "documents verified")
	if err != nil {
		t.Fatalf("expected success, got: %v", err)
	}
	if reviewed.Status != domain.KYCApproved {
		t.Errorf("Status = %s, want APPROVED", reviewed.Status)
	}
	if reviewed.ReviewedBy == nil || *reviewed.ReviewedBy != "admin-uuid" {
		t.Error("ReviewedBy must record the reviewing admin")
	}
}

func TestReviewKYC_RejectDoesNotPromote(t *testing.T) {
	ctx := context.Background()

	roleUpdated := false
	kycRepo := &mockKYCRepo{
		onGetKYCByID: func(ctx context.Context, id string) (*domain.KYCSubmission, error) {
			return &domain.KYCSubmission{ID: id, UserID: "user-uuid-1", TargetRole: domain.RoleVerifiedVendor, Status: domain.KYCPending}, nil
		},
	}
	userRepo := &mockUserRepo{
		onUpdateUserRole: func(ctx context.Context, id string, role domain.UserRole) error {
			roleUpdated = true
			return nil
		},
	}
	uow := &mockUnitOfWork{stores: domain.TxStores{KYC: kycRepo, Users: userRepo}}
	u := newKYCTestUsecase(kycRepo, uow, nil)

	reviewed, err := u.ReviewKYC(ctx, "admin-uuid", "kyc-uuid-1", domain.KYCRejected, "blurry selfie")
	if err != nil {
		t.Fatalf("expected success, got: %v", err)
	}
	if reviewed.Status != domain.KYCRejected {
		t.Errorf("Status = %s, want REJECTED", reviewed.Status)
	}
	if roleUpdated {
		t.Error("a rejected submission must never promote the user role")
	}
}

func TestReviewKYC_AlreadyReviewed(t *testing.T) {
	ctx := context.Background()

	kycRepo := &mockKYCRepo{
		onGetKYCByID: func(ctx context.Context, id string) (*domain.KYCSubmission, error) {
			return &domain.KYCSubmission{ID: id, Status: domain.KYCApproved}, nil
		},
	}
	uow := &mockUnitOfWork{stores: domain.TxStores{KYC: kycRepo}}
	u := newKYCTestUsecase(kycRepo, uow, nil)

	if _, err := u.ReviewKYC(ctx, "admin-uuid", "kyc-uuid-1", domain.KYCApproved, "re-review"); !errors.Is(err, usecase.ErrKYCAlreadyReviewed) {
		t.Fatalf("expected ErrKYCAlreadyReviewed, got: %v", err)
	}
}

func TestReviewKYC_InvalidDecision(t *testing.T) {
	ctx := context.Background()
	u := newKYCTestUsecase(&mockKYCRepo{}, nil, nil)

	if _, err := u.ReviewKYC(ctx, "admin-uuid", "kyc-uuid-1", domain.KYCPending, ""); !errors.Is(err, usecase.ErrKYCInvalidDecision) {
		t.Fatalf("expected ErrKYCInvalidDecision, got: %v", err)
	}
}
