package usecase_test

import (
	"context"
	"testing"

	"rekberkuy/core-service/internal/domain"
	"rekberkuy/core-service/internal/usecase"
)

// ============================================================================
// VENDOR USECASE — UNIT TESTS
// ============================================================================

func TestRegisterVendorProfile_Success(t *testing.T) {
	ctx := context.Background()

	var captured *domain.VendorProfile
	vendorRepo := &mockVendorRepo{
		onCreateVendor: func(ctx context.Context, v *domain.VendorProfile) error {
			captured = v
			return nil
		},
	}
	u := usecase.NewVendorUsecase(vendorRepo)

	input := &domain.VendorProfile{
		VendorID:     "vendor-uuid-1",
		BusinessName: "Katering Sedap",
		Category:     "CATERING",
		IsVerified:   true, // intentionally true to ensure the usecase forces it false
	}

	if err := u.RegisterVendorProfile(ctx, input); err != nil {
		t.Fatalf("expected success, got: %v", err)
	}
	if captured == nil {
		t.Fatal("CreateVendor was not called")
	}
	if captured.IsVerified {
		t.Error("IsVerified must be forced false before admin verification")
	}
}

func TestRegisterVendorProfile_EmptyBusinessName(t *testing.T) {
	ctx := context.Background()
	u := usecase.NewVendorUsecase(&mockVendorRepo{})

	if err := u.RegisterVendorProfile(ctx, &domain.VendorProfile{BusinessName: "", Category: "DECOR"}); err == nil {
		t.Fatal("expected error because BusinessName is empty")
	}
}

func TestRegisterVendorProfile_EmptyCategory(t *testing.T) {
	ctx := context.Background()
	u := usecase.NewVendorUsecase(&mockVendorRepo{})

	if err := u.RegisterVendorProfile(ctx, &domain.VendorProfile{BusinessName: "Foto Jaya", Category: ""}); err == nil {
		t.Fatal("expected error because Category is empty")
	}
}

// ============================================================================
// KYC USECASE — UNIT TESTS
// ============================================================================

func TestSubmitUserKYC_Success(t *testing.T) {
	ctx := context.Background()

	var captured *domain.KYCSubmission
	kycRepo := &mockKYCRepo{
		onSubmitKYC: func(ctx context.Context, k *domain.KYCSubmission) error {
			captured = k
			return nil
		},
	}
	u := usecase.NewKYCUsecase(kycRepo)

	if err := u.SubmitUserKYC(ctx, "user-uuid-1", domain.RoleVerifiedMerchant, "3171010101900001", "https://cdn/ktp.jpg", "https://cdn/selfie.jpg"); err != nil {
		t.Fatalf("expected success, got: %v", err)
	}

	if captured == nil {
		t.Fatal("SubmitKYC was not called")
	}
	if captured.UserID != "user-uuid-1" {
		t.Errorf("UserID = %s, want user-uuid-1", captured.UserID)
	}
	if captured.TargetRole != domain.RoleVerifiedMerchant {
		t.Errorf("TargetRole = %s, want %s", captured.TargetRole, domain.RoleVerifiedMerchant)
	}
	if captured.Status != domain.KYCPending {
		t.Errorf("Status = %s, want PENDING", captured.Status)
	}
	if captured.ID == "" {
		t.Error("KYC ID must be generated by the usecase")
	}
}
